"""Added age column

Revision ID: 1c0aac84a4f6
Revises: 
Create Date: 2025-12-09 08:16:13.346397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0aac84a4f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['category_id'], ondelete='CASCADE')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['address_id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'payment_methods', ['method_id'], ['method_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['brand_id'], ondelete='CASCADE')

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['review_id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('varified', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['role_id'], ondelete='CASCADE')

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'roles', ['role_id'], ['role_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.drop_column('varified')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'reviews', ['review_id'], ['review_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'brands', ['brand_id'], ['brand_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'categories', ['category_id'], ['category_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'payment_methods', ['method_id'], ['method_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'addresses', ['address_id'], ['address_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'categories', ['parent_id'], ['category_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_1'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')

    # ### end Alembic commands ###
