"""Added varified column

Revision ID: 40b9dc014b32
Revises: 1c0aac84a4f6
Create Date: 2025-12-09 08:18:08.681604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40b9dc014b32'
down_revision = '1c0aac84a4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['parent_id'], ['category_id'], ondelete='CASCADE')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'addresses', ['address_id'], ['address_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'payment_methods', ['method_id'], ['method_id'], ondelete='CASCADE')

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['category_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['brand_id'], ondelete='CASCADE')

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'reviews', ['review_id'], ['review_id'], ondelete='CASCADE')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_constraint(batch_op.f('fk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['role_id'], ondelete='CASCADE')

    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_1'))
        batch_op.drop_index(batch_op.f('fk_2'))
        batch_op.drop_constraint(batch_op.f('fk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'roles', ['role_id'], ['role_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['role_id'], unique=False)

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['order_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    with op.batch_alter_table('review_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'reviews', ['review_id'], ['review_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['review_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'brands', ['brand_id'], ['brand_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'categories', ['category_id'], ['category_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['category_id'], unique=False)

    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['product_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'payment_methods', ['method_id'], ['method_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['method_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['order_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'addresses', ['address_id'], ['address_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['address_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'orders', ['order_id'], ['order_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['order_id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['product_id'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'categories', ['parent_id'], ['category_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['parent_id'], unique=False)

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_4'), 'products', ['product_id'], ['product_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_3'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_2'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_2'), 'users', ['user_id'], ['user_id'], referent_schema='test', ondelete='CASCADE')
        batch_op.create_index(batch_op.f('fk_1'), ['user_id'], unique=False)

    # ### end Alembic commands ###
